/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_advantech_scannerwedgedemo_module_ComPortActivity */

#ifndef _Included_com_advantech_scannerwedgedemo_module_ComPortActivity
#define _Included_com_advantech_scannerwedgedemo_module_ComPortActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_advantech_scannerwedgedemo_module_ComPortActivity
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_advantech_scannerwedgedemo_module_ComPortActivity_open
  (JNIEnv *, jobject , jstring, jint, jint);

/*
 * Class:     com_advantech_scannerwedgedemo_module_ComPortActivity
 * Method:    close
 * Signature: (Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_com_advantech_scannerwedgedemo_module_ComPortActivity_close
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
